---
# tasks file for create_multinode
- name: Set IP fact
  set_fact:
    remote_ip: "{{ ansible_host }}"
  when: is_remote

- name: Generate VM list to delete
  delegate_to: localhost
  template:
    src: vm_list.yml.j2
    dest: "{{ vm_list_path }}"

- name: Create nodes
  include_tasks: create.yml
  with_items: "{{ nodes }}"
  vars:
    node: "{{ item }}"
- name: Generate multinode inventory for localhost
  include_tasks: inventory_create.yml

- name: Generate multinode inventory for deployment node
  include_tasks: inventory_create.yml
  vars:
    use_node_names: false
    multinode_file_path: kolla-files/{{ inventory_name }}

- name: Add Proxy Jump to SSH Config
  include_role:
    name: ssh_jump
  when: is_remote
